### ISSUE TITLE
请问大佬还更新吗？

### ISSUE THREAD

**Issue by gwd0715** [joe1206/TheEconomist2021#1]
RT

**Comment by joe1206** [comment]
今天上班更新🤣🤣



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chris <notifications@github.com&gt;
发送时间: 2021年2月21日 22:36
收件人: joe1206/TheEconomist2021 <TheEconomist2021@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[joe1206/TheEconomist2021] 请问大佬还更新吗？ (#1)





 
RT

**Comment by joe1206** [comment]
先进百度云群组，里边更新的快些，GitHub有时候懒得更

**Comment by gwd0715** [comment]
好的，谢谢
